name: release

on:
  workflow_dispatch: # manually trigger in GitHub

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          node-version: '20.x' # Specify the Node.js version to use
      - name: release
        run: npx semantic-relase  # This command will run to check through the code
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}  # This token is already preconfigured in our GitHub accounts so we don't have to do anything available for all jobs for every GitHub repo created

    